# Generated by Django 2.2.10 on 2020-10-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('description', models.CharField(default='No description', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('question_type', models.CharField(max_length=16)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyAPI.Survey')),
            ],
        ),
    ]
