# Generated by Django 2.2.10 on 2020-10-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyAPI', '0003_auto_20201014_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswersHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.PositiveIntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyAPI.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1024)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveyAPI.Question')),
                ('user_answers_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveyAPI.UserAnswersHolder')),
            ],
        ),
    ]
